require 'shellwords'
require 'webconsole'
require WebConsole::shared_test_resource("ruby/test_constants")
require WebConsole::Tests::TEST_HELPER_FILE

task :default => ['wcsearch:tests']

namespace :wcsearch do
  
  task :tests => [:clean_up]

  task :test_parser do
    parser_tests_file = File.join(File.dirname(__FILE__), "tc_parser.rb")
    ruby Shellwords.escape(parser_tests_file)
  end

  task :test_controller => [:test_parser] do
    controller_tests_file = File.join(File.dirname(__FILE__), "tc_controller.rb")
    ruby Shellwords.escape(controller_tests_file)
  end

  task :test_javascript => [:test_controller] do
    javascript_tests_file = File.join(File.dirname(__FILE__), "tc_javascript.rb")
    ruby Shellwords.escape(javascript_tests_file)
  end

  task :test_wcsearch => [:test_javascript] do
    wcsearch_tests_file = File.join(File.dirname(__FILE__), "tc_wcsearch.rb")
    ruby Shellwords.escape(wcsearch_tests_file)
  end

  task :clean_up => [:test_wcsearch] do
    WebConsole::Tests::Helper::quit
  end
end
